pub const BASE_REWARDS_PER_EPOCH: u64 = 4;
pub const DEPOSIT_CONTRACT_TREE_DEPTH: usize = 2usize.pow(5);
pub const JUSTIFICATION_BITS_LENGTH: usize = 4;

#[cfg(not(target_arch = "wasm32"))]
pub const DEPOSIT_DATA_LIST_BOUND: usize = 2usize.pow(DEPOSIT_CONTRACT_TREE_DEPTH as u32);

#[cfg(target_arch = "wasm32")]
//HOPING WE DON'T NEED A BIGGER VALUE
pub const DEPOSIT_DATA_LIST_BOUND: usize = 4_294_967_295;

pub use crate::phase0::networking::{
    ATTESTATION_PROPAGATION_SLOT_RANGE, ATTESTATION_SUBNET_COUNT, GOSSIP_MAX_SIZE,
    MAXIMUM_GOSSIP_CLOCK_DISPARITY, MAX_CHUNK_SIZE, MAX_REQUEST_BLOCKS,
    MIN_EPOCHS_FOR_BLOCK_REQUESTS, RESP_TIMEOUT, TTFB_TIMEOUT,
};
